---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clearml-agent
  name: clearml-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clearml-agent
  template:
    metadata:
      labels:
        app: clearml-agent
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      containers:
        - args:
            - clearml agent start kubernetes -e JUPYTERHUB_API_TOKEN=$JUPYTERHUB_API_TOKEN
          command:
            - /bin/bash
            - -c
          env:
            - name: clearml__CLOUD__AGENT__AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: clearml-token
                  key: clearmlToken
            - name: JUPYTERHUB_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jupyterhub-token
                  key: jupyterHubToken
            - name: clearml__CLOUD__API
              value: https://api.clearml.io
            - name: NAMESPACE
              value: {{ .Values.namespace }}
            - name: IMAGE_PULL_SECRETS
              value: ''
            - name: clearml__CLOUD__AGENT__LABELS
              value: '[]'
            - name: JOB_MEM_REQUEST
              value: ''
            - name: JOB_MEM_LIMIT
              value: ''
            - name: JOB_CPU_REQUEST
              value: ''
            - name: JOB_CPU_LIMIT
              value: ''
            - name: IMAGE_PULL_POLICY
              value: ''
            - name: SERVICE_ACCOUNT_NAME
              value: {{ .Values.serviceAccount }}
            - name: clearml__BACKEND
              value: cloud
            - name: clearml__CLOUD__AGENT__AGENT_ADDRESS
              value: http://:8080
          image: {{ .Values.clearmlImage }}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 40
          name: agent
          resources:
            limits:
              cpu: 100m
              memory: 128Mi

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount }}


